"""Seed default movement information templates."""

import frappe


DEFAULT_MOVEMENT_INFO_TEMPLATES = [
	("Quartz movement", "Watch uses a quartz movement."),
	("Automatic movement", "Watch uses an automatic self-winding movement."),
	("Manual-wind movement", "Watch uses a manual-wind movement."),
	("Chronograph movement", "Watch contains a chronograph complication."),
	("GMT movement", "Watch contains a GMT or dual-time movement."),
	("Day-date movement", "Watch contains both day and date indication."),
	("Moonphase movement", "Watch contains a moonphase complication."),
	("Co-axial movement", "Watch uses a co-axial escapement design."),
	("Solar movement", "Watch uses a solar-powered quartz movement."),
	("Kinetic movement", "Watch uses a kinetic or autoquartz charging system."),
	("Eco-Drive movement", "Watch uses Citizen Eco-Drive light-powered technology."),
	("Mecha-quartz movement", "Watch uses a hybrid mecha-quartz chronograph movement."),
	("Vintage movement", "Movement is from an older or vintage production period."),
	("Swiss movement", "Movement is identified as Swiss manufacture."),
	("Japanese movement", "Movement is identified as Japanese manufacture."),
	("Movement running", "Movement is running during intake or inspection."),
	("Movement not running", "Movement is not running during inspection."),
	("Starts then stops", "Movement starts briefly and then stops."),
	("Irregular rate", "Movement shows unstable or inconsistent timing results."),
	("Beat error elevated", "Movement shows elevated beat error."),
	("Amplitude low", "Movement amplitude is below expected service range."),
	("Timegrapher test pending", "Timing machine test still needs to be performed."),
	("Battery missing", "Quartz movement battery is missing."),
	("Battery leakage present", "Battery leakage is visible in the movement area."),
	("Rotor noise present", "Automatic rotor noise or free-spin is noticeable."),
	("Movement dry", "Movement lubrication is visibly dry or exhausted."),
	("Water damage visible", "Visible water or moisture damage is present in the movement."),
	("Rust visible", "Rust is visible on movement components."),
	("Service marks present", "Previous service marks are visible inside the case or movement."),
	("Movement swapped previously", "Movement appears to have been swapped or replaced previously."),
	("Serial/caliber not matching case", "Movement caliber or serial does not match the case or reference."),
	("2235", "Rolex calibre 2235 automatic movement."),
	("2035", "Rolex calibre 2035 quartz movement."),
	("2135", "Rolex calibre 2135 automatic movement."),
	("3130", "Rolex calibre 3130 automatic movement."),
	("3135", "Rolex calibre 3135 automatic date movement."),
	("3230", "Rolex calibre 3230 automatic movement."),
	("3235", "Rolex calibre 3235 automatic date movement."),
	("3285", "Rolex calibre 3285 GMT automatic movement."),
	("4030", "Rolex calibre 4030 chronograph movement."),
	("4130", "Rolex calibre 4130 chronograph movement."),
	("1570", "Rolex calibre 1570 vintage automatic movement."),
	("2500", "Omega calibre 2500 co-axial automatic movement."),
	("321", "Omega calibre 321 manual chronograph movement."),
	("552", "Omega calibre 552 automatic movement."),
	("565", "Omega calibre 565 automatic date movement."),
	("861", "Omega calibre 861 manual chronograph movement."),
	("8800", "Omega calibre 8800 co-axial automatic movement."),
	("8806", "Omega calibre 8806 co-axial automatic movement."),
	("8900", "Omega calibre 8900 co-axial automatic movement."),
	("8901", "Omega calibre 8901 co-axial automatic movement."),
	("9300", "Omega calibre 9300 co-axial chronograph movement."),
	("9301", "Omega calibre 9301 co-axial chronograph movement."),
	("955.112", "ETA calibre 955.112 quartz movement."),
	("955.114", "ETA calibre 955.114 quartz movement."),
	("956.112", "ETA calibre 956.112 quartz movement."),
	("956.114", "ETA calibre 956.114 quartz movement."),
	("F06.111", "ETA calibre F06.111 quartz movement."),
	("G10.211", "ETA calibre G10.211 quartz chronograph movement."),
	("G10.212", "ETA calibre G10.212 quartz chronograph movement."),
	("2824-2", "ETA calibre 2824-2 automatic movement."),
	("2836-2", "ETA calibre 2836-2 day-date automatic movement."),
	("2892-A2", "ETA calibre 2892-A2 automatic movement."),
	("2671", "ETA calibre 2671 small automatic movement."),
	("7750", "ETA-Valjoux 7750 automatic chronograph movement."),
	("7751", "ETA-Valjoux 7751 calendar chronograph movement."),
	("7753", "ETA-Valjoux 7753 automatic chronograph movement."),
	("6497", "Unitas calibre 6497 manual movement."),
	("6498", "Unitas calibre 6498 manual movement."),
	("SW200-1", "Sellita calibre SW200-1 automatic movement."),
	("SW220-1", "Sellita calibre SW220-1 day-date automatic movement."),
	("SW300-1", "Sellita calibre SW300-1 automatic movement."),
	("SW330-1", "Sellita calibre SW330-1 GMT automatic movement."),
	("SW500", "Sellita calibre SW500 automatic chronograph movement."),
	("7S26", "Seiko calibre 7S26 automatic movement."),
	("7S36", "Seiko calibre 7S36 automatic movement."),
	("4R35", "Seiko calibre 4R35 automatic movement."),
	("4R36", "Seiko calibre 4R36 day-date automatic movement."),
	("4R34", "Seiko calibre 4R34 GMT automatic movement."),
	("6R15", "Seiko calibre 6R15 automatic movement."),
	("6R35", "Seiko calibre 6R35 automatic movement."),
	("6R64", "Seiko calibre 6R64 GMT automatic movement."),
	("8L35", "Seiko calibre 8L35 automatic movement."),
	("NH35", "Seiko/TMI calibre NH35 automatic movement."),
	("NH36", "Seiko/TMI calibre NH36 day-date automatic movement."),
	("NH34", "Seiko/TMI calibre NH34 GMT automatic movement."),
	("VK63", "Seiko/TMI calibre VK63 mecha-quartz chronograph movement."),
	("VK64", "Seiko/TMI calibre VK64 mecha-quartz chronograph movement."),
	("8200", "Miyota calibre 8200 automatic movement."),
	("8215", "Miyota calibre 8215 automatic movement."),
	("8205", "Miyota calibre 8205 day-date automatic movement."),
	("9015", "Miyota calibre 9015 automatic movement."),
	("9039", "Miyota calibre 9039 automatic movement."),
	("9120", "Miyota calibre 9120 multi-function automatic movement."),
	("2035 Ronda", "Ronda calibre 2035 quartz movement."),
	("515", "Ronda calibre 515 quartz movement."),
	("705", "Ronda calibre 705 quartz movement."),
	("715", "Ronda calibre 715 quartz movement."),
	("763", "Ronda calibre 763 quartz movement."),
	("1069", "Ronda calibre 1069 quartz chronograph movement."),
	("1847 MC", "Cartier calibre 1847 MC automatic movement."),
	("P.900", "Panerai calibre P.900 automatic movement."),
	("P.9010", "Panerai calibre P.9010 automatic movement."),
	("L888", "Longines calibre L888 automatic movement."),
	("L619", "Longines calibre L619 automatic movement."),
	("C07.111", "ETA-based Powermatic 80 calibre C07.111 automatic movement."),
	("Powermatic 80", "ETA-derived Powermatic 80 automatic movement family."),
]


def execute():
	"""Create default movement information templates when missing."""
	for movement_info, description in DEFAULT_MOVEMENT_INFO_TEMPLATES:
		if frappe.db.exists("DW Movement Information Template", {"movement_info": movement_info}):
			continue

		frappe.get_doc({
			"doctype": "DW Movement Information Template",
			"movement_info": movement_info,
			"description": description,
			"is_active": 1,
		}).insert(ignore_permissions=True)

	frappe.db.commit()